### ISSUE TITLE
Is not compatible with @angular/core@5.0.2

### ISSUE THREAD

**Issue by omarmd1986** [rsaenen/ng4-validators#1]
├── UNMET PEER DEPENDENCY @ angular/compiler @5.0.2
├── UNMET PEER DEPENDENCY @ angular/core @5.0.2
└── ng4-validators@4.3.5

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN codelyzer@3.2.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.
npm WARN codelyzer@3.2.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.

**Comment by rsaenen** [comment]
The package.json has only devDependencies, I don't get any warnings when I install this package.
Can you show more of your console ?

**Comment by omarmd1986** [comment]
This is almost everything.

npm install --save ng4-validators
angular-tour-of-heroes@0.0.0 /home/omar/NetBeansProjects/angular-tour-of-heroes
├── UNMET PEER DEPENDENCY @ angular/compiler@ 5.0.2
├── UNMET PEER DEPENDENCY @ angular/core@ 5.0.2
└── ng4-validators@ 4.3.5

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN codelyzer@ 3.2.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.
npm WARN codelyzer@ 3.2.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed.

**Comment by omarmd1986** [comment]
I installed the ng-cli.
Create a new ng project using ng new command.
I in the project folder try to install: npm install --save ng4-validators.

**Comment by rsaenen** [comment]
Here's my console output with the following commands `ng new testng4val` and `npm install --save ng4-validators`:
```bash
Project 'testng4val' successfully created.
rsaenen@mateVM:/var/www/html/test$ cd testng4val/
rsaenen@mateVM:/var/www/html/test/testng4val$ npm install --save ng4-validators
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ ng4-validators@4.3.5
added 116 packages in 33.043s
```

My setup:
```bash

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.5.4
Node: 8.6.0
OS: linux x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.4
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.4
@schematics/angular: 0.1.7
typescript: 2.4.2
webpack: 3.8.1
```

Can you paste the output of `ng -v` ?

**Comment by rsaenen** [comment]
Closed due to lack of response.
Please reopen it if necessary.
