### ISSUE TITLE
Bind MinDate and MaxDate validators to a FormControl

### ISSUE THREAD

**Issue by dirkkok101** [rsaenen/ng4-validators#3]
Hi

Would it be possible to support binding Min and Max Date validators to another FormControl similar to the 
EqualTo validator?

For example:
let maxDateControl = new FormControl('', Validators.required);
let minDateControl = new FormControl('', CustomValidators.maxDate(maxDateControl));

**Comment by rsaenen** [comment]
Hi,
I will be released with the next version.
Feel free to contribute to the repository if you need this feat asap.

**Comment by rsaenen** [comment]
I'am unable to publish a new version for now, see [angular/cli#9549](https://github.com/angular/angular-cli/issues/9549).
I won't publish without run tests.

**Comment by rsaenen** [comment]
Released with 5.0.1
