### ISSUE TITLE
Remove @angular/http dependency  

### ISSUE THREAD

**Issue by almothafar** [rsaenen/ng4-validators#6]
May you please remove `@angular/http` as it is deprecated in Angular 5 and causing issues with our project here.

**Comment by almothafar** [comment]
Actually all dependencies must be moved to per and dev instead, I'll try to make pull request today

**Comment by rsaenen** [comment]
Thanks, my bad I didn't move the dependencies to devDependencies as I should.
Dependencies is only usefull to run the demo.

**Comment by almothafar** [comment]
This should be closed in #7
