### ISSUE TITLE
[Angular] Identifier 'email' is not defined. '__type' does not contain such a member

### ISSUE THREAD

**Issue by ikismail** [rsaenen/ng4-validators#8]
Getting Identifier 'email' is not defined. '__type' does not contain such a member

![Error](https://i.imgur.com/KOak0gC.png)

Project is working fine but don't know why this error shows ?

**Environment information**

  - OS: Windows 10 Pro Version 1709
  - Angular Version: 5.2.0
  - Typescript version: 2.5.3
  - npm version: 5.6.0
  - Node Version: 8.11.1

**Comment by rsaenen** [comment]
I can relate... Had the same issue with vscode extension... 
Build is fine, no error in the console but the extensions maybe assume that **errors** typed by **ValidationErrors** has no valid properties.
However this is the definition of **ValidatonErrors**:
```typescript
export declare type ValidationErrors = {
    [key: string]: any;
};
```

I'm pretty sure that an issue is opened for your vscode extension.

**Comment by ikismail** [comment]
Thanks @rsaenen  closing this
