### ISSUE TITLE
Possible to trigger validation check on blur and not on modal change

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [rsaenen/ng4-validators#9]
Is it possible to change the validation to occur only after input blur event and not on modal change?

**Comment by rsaenen** [comment]
Please read the document about `FormGroup`:
https://angular.io/api/forms/FormGroup#example-1

Since Angular 6, you can edit the updateOn value:
```typescript
const c = new FormGroup({
   one: new FormControl()
}, {updateOn: 'blur'});
```

**Comment by VigneshVaidyanathan** [comment]
Thanks, is there any way to do it in Angular 4?

**Comment by rsaenen** [comment]
As this is a new feat, upgrade to v6 is the best option.
